### ISSUE TITLE
HW 2

### ISSUE THREAD

**Issue by tavkhelidzeluka** [NoHorizon/Digital-Academy-Python#1]
https://github.com/NoHorizon/Digital-Academy-Python/blob/9e9dd8ad6aef3b3ce28c73e372e5bf9cc95c8050/Homeworks/homework2/home2%2C%205-1%2C%205-2.py#L17-L18

აქ True მიიღე?

**Comment by tavkhelidzeluka** [comment]
https://github.com/NoHorizon/Digital-Academy-Python/blob/9e9dd8ad6aef3b3ce28c73e372e5bf9cc95c8050/Homeworks/homework2/home2%2C%205-1%2C%205-2.py#L25-L26

აქ მეტია 7-ი 10-ზე?
იმიტომ, რომ გიწერია რო 7 > 10 True იქნებაო

**Comment by tavkhelidzeluka** [comment]
https://github.com/NoHorizon/Digital-Academy-Python/blob/9e9dd8ad6aef3b3ce28c73e372e5bf9cc95c8050/Homeworks/homework2/home2%2C%205-1%2C%205-2.py#L37-L38

მგონი დაგავიწყდა შეგეცვალა True-ბი False-ბად, თუ არადა არასწორად გაქვს ბევრგან.
სულ ყველგან ამბობ, რომ ჭეშმარიტი იქნება პირობა

**Comment by tavkhelidzeluka** [comment]
https://github.com/NoHorizon/Digital-Academy-Python/blob/9e9dd8ad6aef3b3ce28c73e372e5bf9cc95c8050/Homeworks/homework2/home2%2C%205-3%2C%205-7.py#L47-L60

რამე სხვაობას მოგცემს ესე რო დაწერო?
რაში დაგჭირდა იქ შედარება? ისედაც fruit ცვლადი ხომ ჯერ:
banana მერე apple და ბოლოს orange იქნება
```python3
for fruit in favorite_fruits:
    print(f'You really like {fruit.title()}s') 
```

**Comment by NoHorizon** [comment]
დავალება გავიგე ასე, რომ: "შეამოწმეთ თუ არის გარკვეული ხილი სიაში". ამიტომ მაქვს დამატებული If statement-ი. (check whether a certain kind of fruit is in your list, If the fruit is in your list, the if block should print...)

**Comment by NoHorizon** [comment]
> 

მართალი ხართ, ყველგან True დავწერე, ვიფიქრე უბრალოდ "გამოცნობის" თამაშივით იყო. და არ მივანიჭე user-ის "აზრს" მნიშვნელობა.

**Comment by NoHorizon** [comment]
> https://github.com/NoHorizon/Digital-Academy-Python/blob/9e9dd8ad6aef3b3ce28c73e372e5bf9cc95c8050/Homeworks/homework2/home2%2C%205-1%2C%205-2.py#L17-L18
> 
> აქ True მიიღე?

False, ანუ "I predict True" ყველგან დავტოვე რადგან "თამაში მეგონა. ახლა ვხვდები რომ ჩემი prediction იყო საჭირო.
მადლობა შენიშვნებისათვის და გადავაკეთებ.

**Comment by NoHorizon** [comment]
> რამე სხვაობას მოგცემს ესე რო დაწერო?
> რაში დაგჭირდა იქ შედარება? ისედაც fruit ცვლადი ხომ ჯერ:
> banana მერე apple და ბოლოს orange იქნება

დავალება გავიგე ასე, რომ: "შეამოწმეთ თუ არის გარკვეული ხილი სიაში". ამიტომ მაქვს დამატებული If statement-ი. (check whether a certain kind of fruit is in your list, If the fruit is in your list, the if block should print...)

**Comment by tavkhelidzeluka** [comment]
> > რამე სხვაობას მოგცემს ესე რო დაწერო?
> > რაში დაგჭირდა იქ შედარება? ისედაც fruit ცვლადი ხომ ჯერ:
> > banana მერე apple და ბოლოს orange იქნება
> 
> დავალება გავიგე ასე, რომ: "შეამოწმეთ თუ არის გარკვეული ხილი სიაში". ამიტომ მაქვს დამატებული If statement-ი. (check whether a certain kind of fruit is in your list, If the fruit is in your list, the if block should print...)

ციკლი რაღათ გინდა პირდაპირ დაწერე 

```python3
fruit = 'apple'
if fruit in fruits:
    print(f'{fruit} is in fruits')
```

**Comment by NoHorizon** [comment]
> > > რამე სხვაობას მოგცემს ესე რო დაწერო?
> > > რაში დაგჭირდა იქ შედარება? ისედაც fruit ცვლადი ხომ ჯერ:
> > > banana მერე apple და ბოლოს orange იქნება
> > 
> > 
> > დავალება გავიგე ასე, რომ: "შეამოწმეთ თუ არის გარკვეული ხილი სიაში". ამიტომ მაქვს დამატებული If statement-ი. (check whether a certain kind of fruit is in your list, If the fruit is in your list, the if block should print...)
> 
> ციკლი რაღათ გინდა პირდაპირ დაწერე

უი მართალი ხართ, ციკლზე არ წერია არაფერი დავალებაში, 5 if statement არის საჭირო... 
გავასწორებ, მადლობა
